---
- name: copy main configuration file
  template:
    src: templates/{{ configuration_type }}/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: copy apps configuration file
  template:
    src: templates/{{ configuration_type }}/app.conf.j2
    dest: /etc/nginx/conf.d/app.conf

- name: Ensure nginx log directory exists
  ansible.builtin.file:
    path: '/var/log/nginx/{{ ansible_host }}'
    state: directory
    owner: www-data
    group: adm
    mode: '0755'

- name: Ensure nginx access log exists
  ansible.builtin.file:
    path: '/var/log/nginx/{{ ansible_host }}/access.log'
    state: touch
    owner: www-data
    group: adm
    mode: '0644'

- name: Ensure nginx error log exists
  ansible.builtin.file:
    path: '/var/log/nginx/{{ ansible_host }}/error.log'
    state: touch
    owner: www-data
    group: adm
    mode: '0644'

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
