---
- name: Install nginx
  ansible.builtin.package:
    name:
      - nginx
    state: present
    update_cache: yes
  become: yes

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
