---
- name: Install nginx
  ansible.builtin.package:
    name:
      - nginx
    state: present
    update_cache: yes
  become: yes

- name: copy main configuration file
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: copy apps configuration file
  template:
    src: templates/app.conf.j2
    dest: /etc/nginx/conf.d/app.conf

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
