- name: Set up SSH key for vm user
  ansible.builtin.authorized_key:
    user: vm
    key: '{{ ssh_public_key }}'
    state: present

- name: Add host to local known_hosts
  ansible.builtin.known_hosts:
    name: '{{ ansible_host }}'
    key: "{{ lookup('pipe', 'ssh-keyscan -H ' + ansible_host) }}"
    path: '~/.ssh/known_hosts'
  delegate_to: localhost
  run_once: true
  become: false
